[metadata]
version = "1.0"

[versions]
kotlin = "2.3.0"

# polocloud-version
polocloud = "3.0.0-pre.8-SNAPSHOT"

# libraries
gson = "2.13.2"

# rest
javalin = "6.7.0"

jwt = "4.5.0"
javalin-jwt = "0.7.0"

argon2 = "2.12"

log4j = "2.25.4"

[libraries]

log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }

polocloud-proto =  { group = "dev.httpmarco.polocloud", name = "proto", version.ref = "polocloud" }
polocloud-shared =  { group = "dev.httpmarco.polocloud", name = "shared", version.ref = "polocloud" }
polocloud-agent =  { group = "dev.httpmarco.polocloud", name = "agent", version.ref = "polocloud" }
polocloud-common =  { group = "dev.httpmarco.polocloud", name = "common", version.ref = "polocloud" }

# libraries
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# rest
javalin = { group = "io.javalin", name = "javalin", version.ref = "javalin" }
javalin-ssl = { group = "io.javalin.community.ssl", name = "ssl-plugin", version.ref = "javalin" }
java-jwt = { group = "com.auth0", name = "java-jwt", version.ref = "jwt" }
javalin-jwt = { group = "com.github.kmehrunes", name = "javalin-jwt", version.ref = "javalin-jwt" }
argon2 = { group = "de.mkammerer", name = "argon2-jvm", version.ref = "argon2" }

[bundles]
jwt = [ "java-jwt", "javalin-jwt" ]

[plugins]
polocloud-module = { id = "dev.httpmarco.polocloud.module", version.ref = "polocloud" }